name = "qingji"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "qingji-db"
database_id = "fde9c943-756e-4016-963e-4a79a9d6d29e"

[vars]
JWT_SECRET = "qingji-jwt-secret-2026-secure"
